### ISSUE TITLE
方法参数的类型推断不正确

### ISSUE THREAD

**Issue by RJiazhen** [uni-helper/uni-promises#17]
### 描述问题

在使用库导出的方法时，出现ts将其参数推断为`SimpleOptions`类型的情况，导致无法正常出现参数提示。
例如下图中使用showModal方法：
![image](https://github.com/uni-helper/uni-promises/assets/103310338/d490d596-50af-48ae-938e-506e09d99a2a)

### 复现

``` ts
import { showModal } from '@uni-helper/uni-promises';
const res = await showModal({ title: '测试' }); // 对象字面量只能指定已知属性，并且“title”不在类型“SimpleOptions”中。ts(2353)
```
进入到`uni-helper/uni-promises`中查看index.d.ts也发现该方法的类型声明中的参数为`SimpleOptions`类型：
![image](https://github.com/uni-helper/uni-promises/assets/103310338/d07859e5-0f67-4b47-9846-2afa60c940fc)

### 系统信息

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 10.28 GB / 28.92 GB
  Binaries:
    Node: 18.14.0 - C:\Program Files without Authorize\node\node.EXE
    npm: 9.3.1 - C:\Program Files without Authorize\node\npm.CMD
    pnpm: 8.6.5 - C:\Program Files without Authorize\node\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22621.2134.0), Chromium (116.0.1938.76), ChromiumDev (118.0.2060.1)
    Internet Explorer: 11.0.22621.1
```

### 使用的包管理器

npm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [x] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by ModyQyW** [comment]
请试试 0.2.1。一直没有时间更新这个问题非常抱歉 🙏
