### ISSUE TITLE
添加对getFileSystemManager的支持

### ISSUE THREAD

**Issue by MangMax** [uni-helper/uni-promises#22]
### 对问题的清晰和简明的描述

添加对uni.getFileSystemManager()的支持

### 推荐的解决方案

可以将getFileSystemManager提供的方法全部单独promise化然后导出使用

### 检查

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 阅读 [贡献指南](https://github.com/antfu/contribute) 和 [一位疲惫的维护者的笔记](https://github.com/ModyQyW/tired-maintainer)。
- [X] 检查是否已经有一个要求相同功能的问题，以避免重复创建。

**Comment by ModyQyW** [comment]
没有统一支持，暂时不考虑

**Comment by MangMax** [comment]
好的，谢谢回复
